
CREATE SCHEMA IF NOT EXISTS contact DEFAULT CHARACTER SET utf8 ;
USE contact ;

CREATE TABLE IF NOT EXISTS contact.contact  (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  phone VARCHAR(15) NOT NULL,
  email VARCHAR(45) NOT NULL, 
  birth DATETIME(0) NOT NULL,
  delete_at DATETIME(0) NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id ASC) VISIBLE,
  UNIQUE INDEX email_UNIQUE (email ASC) VISIBLE)
ENGINE = InnoDB;

SELECT * FROM contact;